---
abstract: 'JavaScript::Minifier::XS filter for Template Toolkit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
  Template::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Filter-Minify-JavaScript-XS
requires:
  JavaScript::Minifier::XS: 0
  Template: 2.0
  Template::Plugin::Filter: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Filter-Minify-JavaScript-XS
  homepage: http://search.cpan.org/dist/Template-Plugin-Filter-Minify-JavaScript-XS/
  repository: git://github.com/mschout/template-plugin-filter-minify-javascript-xs.git
version: 0.93
